jup_no_password:
	python jupyter_without_password_setup.py

jup_ext:
	./jupyter_extension.sh
# commands requrie sudo    
ctags:
	sudo apt-get -y install exuberant-ctags

openssh:
	sudo apt-get install -y openssh-server
	sudo ufw allow 22

ag:
	sudo apt install -y silversearcher-ag

# for git diff visualization
tig:
	sudo apt-get install -y tig

fzf:
	git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install

tmux-plugins:
	git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm


## MACOS
bash_completion:
	brew install bash-completion

## MACOS
neovim:
	brew install neovim

