jup_no_password:
	python jupyter_without_password_setup.py

jup_ext:
	./jupyter_extension.sh
# commands requrie sudo    
ctags:
	sudo apt-get -y install exuberant-ctags

openssh:
	sudo apt-get install -y openssh-server
	sudo ufw allow 22

ag:
	sudo apt install -y silversearcher-ag

# for git diff visualization
tig:
	sudo apt-get install -y tig

## MACOS
bash_completion:
	brew install bash-completion
